### ISSUE TITLE
Migrate CircleCI pipeline to Github actions

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#141]
# Summary
 Migrate the BitOps CI pipeline which is currently in CircleCI to Github actions.

The same features that are relied on today need to be present after the migration. 
The CircleCI template can be found in [.circleci/config.yml](https://github.com/bitovi/bitops/blob/master/.circleci/config.yml)

CircleCI console; `https://app.circleci.com/pipelines/github/bitovi/bitops?filter=all`

**Comment by RishiKumarRay** [comment]
I would like to work on this.

**Comment by mickmcgrath13** [comment]
@RishiKumarRay Thank you for your interest in contributing to BitOps!

To contribute, please fork [BitOps](https://github.com/bitovi/bitops), make the modifications, and submit a Pull Request.

# Additional Details

## Working with pipelines
As this issue is related to pipeline work, any pipeline configuration will run from your personal account.  This means that you'll need to hook up your own Docker credentials for testing.

## Requirements
- Use the existing `scripts/ci/publish.sh` script (no changes necessary)
- Remove the `.circleci/config.yml` and add a `.github/workflows/build-and-publish.yml` file
- do not commit any sensitive information (i.e. docker login info). Instead, create secrets in the repo, and map them in the pipeline config ([details here](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository))
- do not print any sensitive information in the pipelines (i.e. secrets should not be `echo`d)

### publish script requirements
The required environment variables of the `./scripts/ci/publish.sh` script are:
- `REGISTRY_URL` - the dockerhub registry url (can be hard-coded in the gitlab action definition file. This will need to be `bitovi/bitops` for final merge
- `DOCKER_USER` - the docker registry username. Should be set in github secrets
- `DOCKER_PASS` - the docker registry password. Should be set in github secrets
- `BITOPS_DOCKER_IMAGE_NAME` - should be `bitops`
- `BITOPS_DOCKER_IMAGE_PUBLISH_SKIP_SHA` - skips publishing an image for branches if `BITOPS_DOCKER_IMAGE_PUBLSIH_TAG` is not set. hardcode to "1" in the pipeline config
- `BITOPS_GIT_TAG` - should be set [when a git tag is created.](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) 
- `BITOPS_GIT_SHA` - should be set to the SHA in the pipeline config
- `BITOPS_GIT_BRANCH` - should be set to the branch in the pipeline config ([some details here](https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions))
- `BITOPS_GIT_BASE_BRANCH` - base branch of the repo (use to tag `:latest` if it's the base branch. currently `master` (will change to `main` soon)

### Secrets requirements
https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

Create a repository secret each for `DOCKER_USER` and `DOCKER_PASS` and map in the pipeline config like this:
```
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
```

Hope this helps, and please don't hesitate to ask if you have any questions.

**Comment by mickmcgrath13** [comment]
@RishiKumarRay Just following up here. Do you have any questions about the issue?

**Comment by RishiKumarRay** [comment]
@mickmcgrath13 Hi, Actually I am quite busy so i was unable to start working on this yet but thanks as of now i don't have any questions but I might start working on this late once i get free, sorry for that.

**Comment by mickmcgrath13** [comment]
@RishiKumarRay No problem. Thanks for the update. Let us know if you have any questions.  We'll inform you here if we pick up the issue before you can get to it.
