### ISSUE TITLE
Parse passwords / creditentials out of logging output

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#208]

**Comment by PhillypHenning** [comment]
**AWS**
- access key
- secret access key

**Comment by armab** [comment]
Ideally is to have an option in config `mask_secrets` which would default to `True` (secure by default), allowing users to change it to `False`.
When the `mask_secrets = False`, we should additionally warn user about insecure defaults.

**Comment by armab** [comment]
Research a lib/tool that will mask the secrets from the output.
Parse stdout/stderr line-by-line and apply filtering.

**Comment by mickmcgrath13** [comment]
@PhillypHenning , didn't you mention a tool for this during our last BitOps community call?

**Comment by armab** [comment]
Reopening as https://github.com/bitovi/bitops/pull/345 needs more work, at minimum listing rules for all the possible secrets we have in the https://github.com/bitops-plugins so it's enforced by default.

**Comment by mickmcgrath13** [comment]
Specifically capturing the action items from https://github.com/bitovi/bitops/pull/345
- [ ] change `masks` to `secrets` (https://github.com/bitovi/bitops/pull/345#discussion_r1015825799)
- [ ] default `replace` to `***` (https://github.com/bitovi/bitops/pull/345#discussion_r1015824081)
- [ ] less regex (https://github.com/bitovi/bitops/pull/345#discussion_r1015823461) and use a library (https://github.com/bitovi/bitops/pull/345#discussion_r1015741153)
- [ ] Allow plugins to specify secrets masking
- [ ] Allow operations repos to specify secrets masking
- [ ] Docs

I'll be unable to work on this for quite a while, btw..

In particular on the "how do we define the secrets detection from the bitops config" note (re: https://github.com/bitovi/bitops/pull/345#discussion_r1015823461), @armab said:

---
If we're targeting beginners, I wouldn't expose regex setting in the BitOps config as it brings complexity to the user's side. It's enough to list 10 regex rules to make everything look complicated and repell someone using it.

Other options:
1. Just list the secret vars in bitops core or config. No regex, just BITOPS_KUBECONFIG_BASE64, AWS_SECRET_KEY, etc. and do the rest filtering on the BitOps side.
2. auto-detect secrets in log via heuristics and rules from libs like https://github.com/Yelp/detect-secrets/tree/master/detect_secrets/plugins
3. allow specifying extra secret names on top of default/hardcoded

```
secrets:
  - BITOPS_KUBECONFIG_BASE64
  - AWS_SECRET_ACCESS_KEY
  - AWS_ACCESS_KEY_ID
  - AWS_SESSION_TOKEN
```

Alternatively, allow defining secrets on BitOps Plugin level and process in the code so the secret definition is pluggable.
---

My thoughts on the above:
## 1) secrets list or object
 I don't think a straight "secrets:" list as you've described above will be sufficient. That will be good for env vars, but there are other things/formats we'll want to cover (and ensure are configurable somehow for others to handle) such as json, yaml (helm output, for example), etc.

What if we provided something more like:
```
secrets:
  # handles things like `ENV_VAR_A=foo`, `ENV_VAR_B.       ="foo"`, etc
  env:
    - BITOPS_KUBECONFIG_BASE64
    - AWS_SECRET_ACCESS_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SESSION_TOKEN

  # handles values of json objects like `{"foo": "bar", "aws_secret_access_key": "asdf"}`
  json_object:
    - aws_secret_access_key

  # handles arbitrary regex strings
  regex:
    - (.*BITOPS_KUBECONFIG_BASE64.*\=)(.*\n)
```
..of course, we could default many/most/all of these, but I think it'd be good to provide a way for people to define their own.


## 2. auto-detect secrets
> auto-detect secrets in log via heuristics and rules from libs like https://github.com/Yelp/detect-secrets/tree/master/detect_secrets/plugins

We should absolutely do this.  I'd expect a simple interface per line of output (since we're outputting line-by-line) to the effect of `masked_line_of_output = secrets_masker(line_of_output)`.  It looks like the linked library (Yelp/detect-secrets) would take some work/investigation to see if/how we can achieve this (it seems to be file based).

## 3. allow specifying extra secret names on top of default/hardcoded
again, we should absolutely do this (see number 1 above)

## 4. Specifying secrets masking by plugins
Perhaps plugins could provide something like what is outlined in number 1 above in the `plugin.config.yaml`?

**Comment by armab** [comment]
Done in v2.3.0

https://github.com/bitovi/bitops/pull/345
https://github.com/bitovi/bitops/pull/381

If we need more, let's create a new issue.
