### ISSUE TITLE
ENVIORMENT message on docker run is wrong 

### ISSUE THREAD

**Issue by ivorsmorenburg** [bitovi/bitops#283]
**Describe the bug**
The message reporting the error of not defining the ENV has the old env keyword "**ENVIRONMENT**" which at the moment is change to be **BITOPS_ENVIRONMENT**"
**To Reproduce**
1. Docker run with ENVIRONMENT="example_env"
2. Click on execute
3. Scroll down to see the error of not setting the ENVIRONMENT when actually should be BITOPS_ENVIRONMENT

**Expected behavior**
Reporting the actual error

*System info*
* BitOps image tag used: latest
* Hardware: mac
* Tool: docker

**Additional context**
It will be nice to update the error message reporting the right ENV  var to use

**Comment by armab** [comment]
Thanks @ivorsmorenburg for reporting this!

This was indeed an issue in the [2.0.0-rc release candidate](https://github.com/bitovi/bitops/releases/tag/v2.0.0-rc). The fixed version will be rolled out as part of the `2.0.0` release soon.

In a meantime, you can try checking with the `bitovi/bitops:dev` Docker image which is a current development version to confirm if the issue is fixed for you.
