### ISSUE TITLE
Terraform version its too low

### ISSUE THREAD

**Issue by ivorsmorenburg** [bitovi/bitops#307]
**Describe the bug**
Terraform version is too low and doesnt work terraform.options.version: "1.3.0" in bitops.onfig.yaml
**To Reproduce**

**Expected behavior**
BitOps should use that version

*System info*
* BitOps image tag used: 2.0.0
* Hardware: docker
* Tool: terraform

**Comment by mickmcgrath13** [comment]
Thanks for the issue @ivorsmorenburg!

> BitOps should use that version

Which version should be used?  1.3.0?

For a little context, the TF version is determined by the TF plugin: 
https://github.com/bitops-plugins/terraform/blob/main/install.sh#L13

We could take several approaches here:
1) install multiple versions of TF by the plugin
This would probably be good for the Omnibus image, though it would add a bit of bloat.

2) Implement a versioning strategy for the TF plugin
this is something we should admittedly do anyway.  The question is:
should the plugin version equal the TF version that is installed in it?

2.1) If we use the same TF version for the plugin version, there would be a bit of ambiguity in additional features of the plugin (e.g. if the terraform version is 1.3.0, but we add a new feature to the plugin, do we update the plugin version?).

2.2) It might make sense to version the TF plugin independently of the TF version and suffix the version with the TF version.  Something like `1.0.0-tf1.3.0`.  

3) Fork the terraform plugin
Users can fork the terraform plugin and modify as-needed, then create a custom docker container ([docs](https://bitovi.github.io/bitops/plugins/#creating-your-own-bitops-image))

One caveat with this approach is that it's additional overhead for users.


My preference would be option 2.2 (version the tf plugin version and tf version independently).

@armab thoughts?

**Comment by mickmcgrath13** [comment]
fwiw, there's a discussion here that we could prioritize:
https://github.com/bitovi/bitops/discussions/206

**Comment by armab** [comment]
When you're using the pre-defined BitOps image from Docker Hub, the Terraform version is already pre-packaged and it's not possible to control that from the `bitops.config.yaml`.

You could build your own BitOps image with a list of tools and versions you need. See https://bitovi.github.io/bitops/plugins/#creating-your-own-bitops-image.
However, an issue is that Terraform version is hardcoded there.


I see 3 issues here:
- Validation: BitOps should throw an error when trying to overwrite plugin settings `terraform.options.version: "1.3.0"` for a prebuilt BitOps image or using an inexistent setting. Bug #237 
- Terraform version is [hardcoded](https://github.com/bitops-plugins/terraform/blob/b189c2dd7cb38e7e883837f0f3204e5b7e8a6e6b/install.sh#L12-L14) in the plugin
- [Missing version configuration](https://github.com/bitops-plugins/terraform/blob/b189c2dd7cb38e7e883837f0f3204e5b7e8a6e6b/bitops.schema.yaml#L27-L30) for terraform plugin

**Comment by ivorsmorenburg** [comment]
Thanks for all the info, don't think building my own image, or using a plugin, I see too much overwork for changing just the version. 

No issues running that against the schema, it run fine but with the version already hardcoded in bitops andn ot the one specified.

**Comment by ivorsmorenburg** [comment]
Can we upgrade it to 1.3.0 ? 😄

**Comment by armab** [comment]
> No issues running that against the schema, it run fine

Yeah, the bug here is that when you set a version in config `terraform.options.version: "1.3.0"` it didn't work, making you feel it worked instead of showing an error about an inexistent setting. #117 

> Can we upgrade bitops to use TF 1.3.0 ? 
Sure. I'd assume when using an official BitOps image, do you expect to have everything `latest` by default in the tools we package, right https://bitovi.github.io/bitops/versioning/#official-images?

**Comment by ivorsmorenburg** [comment]
That's exactly my expectation :). Thanks!!!

**Comment by armab** [comment]
@ivorsmorenburg Sounds good. We'll bump the versions for all the tools and update you here.
It will likely come with the BitOps `v2.1.0` image tag in the next several days.

**Comment by armab** [comment]
@ivorsmorenburg Nice! Worth exploring, thanks for the link 👍 

Allowing switching the plugin version on fly for the Omnibus image via config would be nice, but then we should pre-package many versions for each tool as a rule and be consistent in our approach. It can take significant space for Ansible + Terraform + AWS + kubectl, etc, etc and fit everyone's needs to have several major + minor versions.

@mickmcgrath13 We can package a couple of terraform binaries, but that is rather a fix that doesn't scale, because there are other tools and versions.

The questions:
- how many major/minor versions do we want to pre-package for each tool?
- what if user-version specified is not what we pre-packaged?
- what to do with the patch versions, security fixes/updates for each major.minor?
- how much space overhead it'll take?

We could potentially experiment with that and see where it goes, but feels like the scalability is not there.
Alternative is allowing user to specify a version in the bitops config for the custom image they build (https://bitovi.github.io/bitops/plugins/#creating-your-own-bitops-image), while using all latest version for official pre-packaged BitOps images.

All approaches with their pros/cons.

**Comment by mickmcgrath13** [comment]
I agree.  
1) Adding multiple binaries adds bloat that not everyone would want and doesn't scale (has implications of how many versions do we support)
2) Allowing on-demand TF versions adds to startup time of the tool (if not pre-packaged, it takes time to install for every deployment vs pre-packaged)
3) forcing users to create their own image is _probably_ the most scalable approach but doesn't help for 'quick start' scenarios

I wonder if the best approach would be a hybrid of all?

1) we provide a pre-packaged set of common versions that can be selected via the `terraform.options.version`.  with this, we could also probably provide versioned plugins with the `1.0.0-tf1.3.0` approach.
2) if the version does not exist, we install it on the fly (with something like https://github.com/tfutils/tfenv)
3) users can lower the deployment time/latency by creating their own image with succinct tf versions

additionally, we should have better error/warning messages about what happens when the `terraform.options.version` doesn't match what's installed/pre-packaged.

..and in any case, we need a consistent, reliable, quick way to ensure we can accommodate the use case of providing specific versions for tools.

for @ivorsmorenburg's immediate case, I think either 
1) pre-installing multiple binaries (this would get us closer to the above hybrid approach)
2) we create a `1.0.0-tf1.3.0` version of the tf plugin and release a new omnibus image

**Comment by mickmcgrath13** [comment]
one other note:  I am wary of simply upgrading the [version of the plugin's installed tf](https://github.com/bitops-plugins/terraform/blob/main/install.sh#L13) from 1.2.2 to 1.3.0 in case there are breaking changes with existing ops repos that rely on 1.2.2.  Is that a legitimate concern?

**Comment by ivorsmorenburg** [comment]
That's why having on-demand terraform versions its a very helpful thing for 'quick start' and more complex scenarios. Thats why with tfenv you define the version in each module [.terraform-version](https://github.com/tfutils/tfenv#terraform-version-file). 
It could take some time to download and install (few seconds) but that could be optional with a default binary in the image and the ability to switch if required. 

This is very scalable, as the version its not a dependency. I see a lot of benefits having something like this.

**Comment by armab** [comment]
Terraform is easy as that's just a binary image to download. If we want to be consistent in our approach, how do we properly support other versions and tools, say Ansible, which can take some time to build on fly (sometimes minutes, depending on the version because some sources have to rebuilt)?

What if there are multiple versions the user is specifying for the Omnibus image: https://bitovi.github.io/bitops/versioning/#official-images
* terraform
* was-cli
* ansible
* helm 
* kubectl
^^ all of that?

how much time that'll take together and what would be the user experience with BitOps? more importantly, what if BitOps plugin could install ansible `v2.9`, but the build/install fails on installing ansible `v2.8` and the image is part of the production deployment pipeline?

**Comment by armab** [comment]
> one other note: I am wary of simply upgrading the [version of the plugin's installed tf](https://github.com/bitops-plugins/terraform/blob/main/install.sh#L13) from 1.2.2 to 1.3.0 in case there are breaking changes with existing ops repos that rely on 1.2.2. Is that a legitimate concern?

If we'll release it under the new BitOps `v2.1.0` tag, folks who have pinned `v2.0.0` won't have any breaking changes.

I'd also recommend all the future official BitOps images to rely on the "latest" tools, rather than on pinned.

* https://github.com/bitops-plugins/kubectl/blob/458d9c144c13073e4afa84cce8023aa4c68bbad5/install.sh#L17
* https://github.com/bitops-plugins/terraform/blob/b189c2dd7cb38e7e883837f0f3204e5b7e8a6e6b/install.sh#L13
* https://github.com/bitops-plugins/ansible/blob/29af954b11406546160229f60a23967ee42029c4/install.sh#L26
* https://github.com/bitops-plugins/helm/blob/cadf9eb0922d8d072735c41ee6c9c725cef0522a/install.sh#L14

We say that the latest BitOps images are built based on the latest tools by default as that's probably the most expected behaviour. Agree?

**Comment by armab** [comment]
@mickmcgrath13 Just replied on the versioning strategy here: https://github.com/bitovi/bitops/discussions/206#discussioncomment-3800223.

**Comment by mickmcgrath13** [comment]
@armab responded here: https://github.com/bitovi/bitops/discussions/206#discussioncomment-3809131

@armab, @ivorsmorenburg I've approved all the plugin PRs to install latest for each tool rather than pinning.

Next Steps:
- Merge all PRs
- New Omnibus image
  - Release notes and docs updates

**Comment by armab** [comment]
@ivorsmorenburg The new BitOps image version is not released yet. Will be coming soon as `v2.1.0`.

**Comment by armab** [comment]
There are still some ongoing fixes left https://github.com/bitovi/bitops/milestone/7 that would be nice to include in this release. We should get the v2.1.0 out this week.

**Comment by armab** [comment]
@ivorsmorenburg The v2.1.0 release is out. https://github.com/bitovi/bitops/releases/tag/v2.1.0 has information about the tools packaged in the latest official BitOps image, including latest Terraform.

You can use `bitovi/bitops:latest` image or if you prefer pinning: `bitovi/bitops:2.1.0`.
Docker hub: https://hub.docker.com/r/bitovi/bitops/tags

Thanks a lot for raising the initial issue, it helped us to improve the tool 👍
