### ISSUE TITLE
Only deploy envs and sub-env-folders with files that have changed in the latest commit

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#32]
## Problem
Sometimes not much changes in a commit but BitOps still deploys everything.

For example, with helm, bitops [iterates all charts](https://github.com/bitovi/bitops/blob/master/scripts/helm/deploy.sh#L14) in `${ENVIRONMENT}/helm/*`, but if we only changed one of the charts, we don't need to deploy everything necessarily.

## Solution
Check the git commit information for which files have changed and only deploy things that match.

Example:
```
   HAS_CHANGES="$(git diff --name-only HEAD HEAD^|grep $helm_chart_dir|cut -d/ -f3|sort -u)"
    if [ -n "$HAS_CHANGES" ]; then
      echo "Deploy $helm_chart_dir for $ENVIRONMENT"
      $SCRIPTS_DIR/helm/deploy-chart.sh $helm_chart_dir
    else
      echo "No changes detected in $helm_chart_dir helm chart for $ENVIRONMENT..skipping deployment"
    fi
```

## Considerations
- need a flag to opt in/out of this functionality

**Comment by ConnorGraham** [comment]
Slightly different context, but this should be expanded to do more than selectively deploy Helm charts. It should also select the whole ops repo `ENVIRONMENT`, if not provided

Instead of providing the `ENVIRONMENT` env var on every BitOps run, it would be nice if there was an auto or git mode that would auto-detect what environment to run based on what has changed in the latest commit to the ops repo

**Comment by mickmcgrath13** [comment]
@ConnorGraham for the second part, I created a new ticket here: https://github.com/bitovi/bitops/issues/94
